function data = load_file(filepath)
  %Time (s)	Wheel Position (deg)	Slide position (mm)	Wheel Speed (deg/s)	Slide Speed (mm/s)	Actual sample time (ms)	%2/9/20163:09 PM
  raw_data = load(filepath);
  data = struct('times',                 [], ...
                'wheel_position',        [], ...
                'slide_position',        [], ...
                'wheel_speed',           [], ...
                'slide_speed',           [], ...
                'actual_sample_time_ms', [], ...
                'filename', filepath         ...
  );

  data.times                 = raw_data(:, 1);
  data.wheel_position        = raw_data(:, 2);
  data.slide_position        = raw_data(:, 3);
  data.wheel_speed           = raw_data(:, 4);
  data.slide_speed           = raw_data(:, 5);
  data.actual_sample_time_ms = raw_data(:, 6);
end
